#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

cd "$repo_root"

{
  echo "# Repository Structure"
  echo
  echo "This file is generated by \`tools/scripts/generate-repo-structure.sh\`."
  echo "Do not edit by hand."
  echo
  echo '```'
  tree -a --dirsfirst -I '.git|.DS_Store'
  echo '```'
} > docs/repo-structure.md

echo "Wrote docs/repo-structure.md"
