[platformio]
default_envs = waveshare_esp32_s3_eth

[env:waveshare_esp32_s3_eth]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D EBUS_UART_RX_PIN=16
  -D EBUS_UART_PORT=1
  -D EBUS_UART_BAUD=2400
  -D USB_LOG_BAUD=115200
  -D EBUS_IDLE_GAP_US=20000
  -D EBUS_SUMMARY_INTERVAL_MS=5000
  -D EBUS_DRIVER_RX_BUFFER=1024
  -D EBUS_FRAME_BUFFER_BYTES=256
  -D EBUS_EVENT_QUEUE_LENGTH=32

